Feat/async img wait (#49)
* Deploy capi-image in background and wait. (#42)

This implements improvement (issue) #42.

Signed-off-by: Kurt Garloff <kurt@garloff.de>

* Add standard SCS image metadata.

Signed-off-by: Kurt Garloff <kurt@garloff.de>

* Avoid terraform template syntax.

Signed-off-by: Kurt Garloff <kurt@garloff.de>

* Fix typos and use variables to simplify things.

Signed-off-by: Kurt Garloff <kurt@garloff.de>

* Add kubernetes_version.

Also comment out wait for capi-webhooks pod which is no longer there.

Signed-off-by: Kurt Garloff <kurt@garloff.de>

diff --git a/terraform/files/template/upload_capi_image.sh.tmpl b/terraform/files/template/upload_capi_image.sh.tmpl
--- a/terraform/files/template/upload_capi_image.sh.tmpl
+++ b/terraform/files/template/upload_capi_image.sh.tmpl
@@ -3,20 +3,43 @@
 KUBERNETES_VERSION="${kubernetes_version}"
 VERSION_CAPI_IMAGE=$(echo $KUBERNETES_VERSION | sed 's/\.[[:digit:]]*$//g')
 PROVIDER="${provider}"
-
+IMGREG_EXTRA="${image_registration_extra_flags}"
+UBU_IMG=ubuntu-2004-kube-$KUBERNETES_VERSION
+UBU_IMG_NM=ubuntu-capi-image-$KUBERNETES_VERSION
 
 #install Openstack CLI
 sudo apt install -y python3-openstackclient
 
 #download/upload image to openstack
-CAPIIMG=$(openstack --os-cloud $PROVIDER image list --name ubuntu-capi-image-$KUBERNETES_VERSION)
+CAPIIMG=$(openstack --os-cloud $PROVIDER image list --name $UBU_IMG_NM)
 if test -z "$CAPIIMG"; then
   # TODO: Check signature
-  wget https://images.osism.tech/openstack-k8s-capi-images/ubuntu-2004-kube-$VERSION_CAPI_IMAGE/ubuntu-2004-kube-$KUBERNETES_VERSION.qcow2
+  wget https://images.osism.tech/openstack-k8s-capi-images/ubuntu-2004-kube-$VERSION_CAPI_IMAGE/$UBU_IMG.qcow2
   FMT=qcow2
+  IMGINFO=$(qemu-img info $UBU_IMG.qcow2)
+  DIKKSZ=$(echo "$IMGINFO" | grep '^virtual size' | sed 's/^[^(]*(\([0-9]*\) bytes).*$/\1/')
+  DISKSZ=$(((DISKSZ+1073741823)/1073741824))
+  IMGDATE=$(date -r $UBU_IMG.qcow2 +%F)
   if test "${kube_image_raw}" = "true"; then
     FMT=raw
-    qemu-img convert ubuntu-2004-kube-$KUBERNETES_VERSION.qcow2 -O raw -S 4k ubuntu-2004-kube-$KUBERNETES_VERSION.raw && rm ubuntu-2004-kube-$KUBERNETES_VERSION.qcow2
+    qemu-img convert $UBU_IMG.qcow2 -O raw -S 4k $UBU_IMG.raw && rm $UBU_IMG.qcow2 || exit 1
   fi
-  openstack --os-cloud $PROVIDER image create --disk-format $FMT --file ubuntu-2004-kube-$KUBERNETES_VERSION.$FMT ubuntu-capi-image-$KUBERNETES_VERSION # && rm  ubuntu-2004-kube-$VERSION_CAPI_IMAGE.$FMT
+  #TODO min-disk, min-ram, other std. image metadata
+  openstack --os-cloud $PROVIDER image create --disk-format $FMT --min-ram 1024 --min-disk $DISKSZ --property image_build_date="$IMGDATE" --property image_original_user=ubuntu --property architecture=x86_64 --property hypervisor_type=kvm --property os_distro=ubuntu --property os_version="20.04" --property hw_disk_bus=scsi --property hw_scsi_model=virtio-scsi --property hw_rng_model=virtio --property image_source=https://images.osism.tech/openstack-k8s-capi-images/ubuntu-2004-kube-$VERSION_CAPI_IMAGE/$UBU_IMG.qcow2 --property kubernetes_version=$KUBERNETES_VERSION --tag managed_by_osism $IMGREG_EXTRA --file $UBU_IMG.$FMT $UBU_IMG_NM &
+  sleep 5
+  echo "Waiting for image $UBU_IMG_NM: "
+  let -i ctr=0
+  while test $ctr -lt 60; do
+    CAPIIMG=$(openstack --os-cloud $PROVIDER image list --name $UBU_IMG_NM -f value -c ID -c Status)
+    STATUS="$${CAPIIMG##* }"
+    if test "$STATUS" = "saving" -o "$STATUS" = "active"; then break; fi
+    echo -n "."
+    let ctr+=1
+    sleep 10
+  done
+  echo " $CAPIIMG"
+  if test $ctr -ge 60; then
+    echo "ERROR: Image $UBU_IMG_NM not found" 1>&2
+    exit 2
+  fi
 fi
