Fix typos and use variables to simplify things.
Signed-off-by: Kurt Garloff <kurt@garloff.de>

diff --git a/terraform/files/template/wait_capi_image.sh.tmpl b/terraform/files/template/wait_capi_image.sh.tmpl
--- a/terraform/files/template/wait_capi_image.sh.tmpl
+++ b/terraform/files/template/wait_capi_image.sh.tmpl
@@ -1,16 +1,16 @@
 #!/usr/bin/env bash
 
 KUBERNETES_VERSION="${kubernetes_version}"
-VERSION_CAPI_IMAGE=$(echo $KUBERNETES_VERSION | sed 's/\.[[:digit:]]*$//g')
 PROVIDER="${provider}"
+UBU_IMG_NM=ubuntu-capi-image-$KUBERNETES_VERSION
 
 #download/upload image to openstack
 echo -n "Waiting for image $CAPIIMG to become active: "
 let -i ctr=0
 while test $ctr -lt 180; do
-  CAPIIMG=$(openstack --os-cloud $PROVIDER image list --name ubuntu-capi-image-$KUBERNETES_VERSION -f value -c ID -c Status)
+  CAPIIMG=$(openstack --os-cloud $PROVIDER image list --name $UBU_IMG_NM -f value -c ID -c Status)
   if test -z "$CAPIIMG"; then
-    echo; echo "ERROR: Image ubuntu-capi-image-$KUBERNETES_VERSION does not exist" 1>&2; exit 1
+    echo; echo "ERROR: Image $UBU_IMG_NM does not exist" 1>&2; exit 1
   fi
   if test "$${CAPIIMG##* }" = "active"; then echo "$CAPIIMG"; break; fi
   echo -n "."
